[build]
  command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable && source $HOME/.cargo/env && cargo install dioxus-cli --locked && dx build --release && echo '/* /index.html 200' > target/dx/telcoin-explorer/release/web/public/_redirects"
  publish = "target/dx/telcoin-explorer/release/web/public"

[build.environment]
  RUST_LOG = "info"
